version: "3"

services:
  web:
    build: .
    image: virink/gkctf_2020_web_view_headers
    restart: always
    ports:
      - "8085:80"
    environment:
      - FLAG=gkctf{gkctf_2020_web_view_headers}
